# Configuración del sitio
title: Tu Sitio
description: Descripción de tu sitio
url: https://mgrl39.github.io  # Asegúrate de poner tu URL de GitHub Pages

# Configuración de Jekyll
theme: jekyll-dash
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"

# Configuración de Disqus
disqus:
  shortname: <tu-shortname-de-disqus>  # Si usas Disqus, coloca aquí tu shortname

# Configuración de la fecha
dash:
  date_format: "%b %-d, %Y"

# Configuración de la animación de entrada de las publicaciones
animation_speed: 50

# Configuración del soporte RTL
rtl: false

# Configuración del avatar
#avatar_source: github
#github_username: bitbrain
#avatar_source: local
#avatar_path: /assets/avatar.png

# Enlaces sociales
social_links:
  - url: https://twitter.com/bitbrain_
    icon: twitter-square
    color: cyan
  - url: https://bitbrain.itch.io
    icon: itch-io
    color: red
  - url: https://github.com/bitbrain
    icon: github-square
    color: purple

# Configuración del autor
show_author: true

# Configuración de los plugins
plugins:
  - jekyll-paginate
  - jekyll-tagging
